package com.yamareviewer.domain.ids;

import java.util.Collections;
import java.util.EnumSet;
import java.util.Set;

/** Everything the plugin needs to recognise, by what it means rather than by number (spec 5.5). */
public enum Role
{
	YAMA(RoleKind.NPC),
	JUDGE(RoleKind.NPC),
	VOID_FLARE(RoleKind.NPC),
	VOICE_OF_YAMA(RoleKind.NPC),
	METEOR_NPC(RoleKind.NPC),
	JUDGE_FIRE_SURGE(RoleKind.NPC),

	YAMAS_DOMAIN(RoleKind.REGION),

	PHASE_TRANSITION_TEXT(RoleKind.OVERHEAD),

	PRAYER_DISABLED_MESSAGE(RoleKind.MESSAGE),
	GLYPH_CONJURE_MESSAGE(RoleKind.MESSAGE),

	PHASE_VARBIT(RoleKind.VARBIT),

	CONTRACT_NAME_WIDGET(RoleKind.WIDGET),

	CONTRACT_ITEM_FORFEIT_BREATH(RoleKind.ITEM),
	CONTRACT_ITEM_GLYPHIC_ATTENUATION(RoleKind.ITEM),
	CONTRACT_ITEM_SENSORY_CLOUDING(RoleKind.ITEM),
	CONTRACT_ITEM_DIVINE_SEVERANCE(RoleKind.ITEM),
	CONTRACT_ITEM_BLOODIED_BLOWS(RoleKind.ITEM),
	CONTRACT_ITEM_FAMILIAR(RoleKind.ITEM),
	CONTRACT_ITEM_CATALYST(RoleKind.ITEM),
	CONTRACT_ITEM_WORM(RoleKind.ITEM),
	CONTRACT_ITEM_SHARD(RoleKind.ITEM),
	CONTRACT_ITEM_OATHPLATE(RoleKind.ITEM),
	CONTRACT_ITEM_HARMONY(RoleKind.ITEM),
	WEAPON_EMBERLIGHT(RoleKind.ITEM),
	WEAPON_ELDER_MAUL(RoleKind.ITEM),
	WEAPON_DRAGON_WARHAMMER(RoleKind.ITEM),
	WEAPON_BANDOS_GODSWORD(RoleKind.ITEM),
	WEAPON_ACCURSED_SCEPTRE(RoleKind.ITEM),
	WEAPON_EYE_OF_AYAK(RoleKind.ITEM),
	WEAPON_SOULFLAME_HORN(RoleKind.ITEM),
	WEAPON_PURGING_STAFF(RoleKind.ITEM),
	WEAPON_SARADOMIN_GODSWORD(RoleKind.ITEM),

	GLYPH_FIRE(RoleKind.OBJECT),
	GLYPH_SHADOW(RoleKind.OBJECT),

	YAMA_STANDARD_ATTACK(RoleKind.ANIMATION),
	YAMA_MELEE(RoleKind.ANIMATION),
	YAMA_FLARE_SUMMON(RoleKind.ANIMATION),
	SHADOW_STOMP(RoleKind.ANIMATION),
	FLARE_EXPLODE(RoleKind.ANIMATION),
	FLARE_DEATH(RoleKind.ANIMATION),
	SPEC_EMBERLIGHT(RoleKind.ANIMATION),
	SPEC_ELDER_MAUL(RoleKind.ANIMATION),
	SPEC_DRAGON_WARHAMMER(RoleKind.ANIMATION),
	SPEC_BANDOS_GODSWORD(RoleKind.ANIMATION),
	SPEC_ACCURSED_SCEPTRE(RoleKind.ANIMATION),
	SPEC_EYE_OF_AYAK(RoleKind.ANIMATION),
	SPEC_SOULFLAME_HORN(RoleKind.ANIMATION),
	SPEC_PURGING_STAFF(RoleKind.ANIMATION),
	SPEC_SARADOMIN_GODSWORD(RoleKind.ANIMATION),

	YAMA_CAST_MAGIC(RoleKind.GRAPHIC),
	YAMA_CAST_RANGED(RoleKind.GRAPHIC),
	IMPACT_MAGIC(RoleKind.GRAPHIC),
	IMPACT_RANGED(RoleKind.GRAPHIC),
	CRASH_IMPACT(RoleKind.GRAPHIC),
	CRASH_FIREBALL(RoleKind.GRAPHIC),
	SHADOW_WAVE(RoleKind.GRAPHIC),
	FIRE_STREAK(RoleKind.GRAPHIC),
	FIRE_ATTACK(RoleKind.GRAPHIC),
	METEOR_STRIKE(RoleKind.GRAPHIC),
	GLYPH_PROTECTION(RoleKind.GRAPHIC),
	PHASE_TRANSITION_GRAPHIC(RoleKind.GRAPHIC),
	FLARE_HEAL(RoleKind.GRAPHIC),
	FLARE_HIT(RoleKind.GRAPHIC),
	SHADOW_POOL(RoleKind.GRAPHIC);

	/** The eleven contract items, one role per contract (spec 6.3.1). */
	public static final Set<Role> CONTRACT_ITEMS = Collections.unmodifiableSet(EnumSet.of(
		CONTRACT_ITEM_FORFEIT_BREATH, CONTRACT_ITEM_GLYPHIC_ATTENUATION, CONTRACT_ITEM_SENSORY_CLOUDING,
		CONTRACT_ITEM_DIVINE_SEVERANCE, CONTRACT_ITEM_BLOODIED_BLOWS, CONTRACT_ITEM_FAMILIAR,
		CONTRACT_ITEM_CATALYST, CONTRACT_ITEM_WORM, CONTRACT_ITEM_SHARD, CONTRACT_ITEM_OATHPLATE,
		CONTRACT_ITEM_HARMONY));

	private final RoleKind kind;

	Role(RoleKind kind)
	{
		this.kind = kind;
	}

	public RoleKind kind()
	{
		return kind;
	}
}
